def plot_data():
    ...
    
def plot_model_exploration():
    ...

def plot_model_prior_samples(N):
    ...

def plot_model_maximum_posterior():
    ...
    
def sample_posterior():
    samples = ...
    return samples

def plot_posterior_samples(samples):
    ...

def plot_model_posterior_samples(samples, N):
    ...